FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /receiver ./cmd/receiver

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /receiver /receiver
EXPOSE 9090
ENTRYPOINT ["/receiver"]


